-- xplane_bridge_generated.lua
-- Auto-generated by generate_xplane_bridge.lua
-- Reads UDP payloads from failure bot and applies mapped outputs in X-Plane 12.

local function safe_require(module_name)
  local ok, mod = pcall(require, module_name)
  if ok then
    return mod
  end
  return nil
end

local socket = safe_require("socket")
if not socket then
  print("[xplane-bridge] missing LuaSocket")
  return
end

local config = {
  listen_port = 49000,
  standalone_mode = false,
  mappings = {
    engine = {
      target = "sim/operation/failures/rel_engfir1",
      write_mode = "int",
      active_value = 6,
      inactive_value = 0,
    },
    hydraulics = {
      target = "sim/operation/failures/rel_hyd1",
      write_mode = "int",
      active_value = 6,
      inactive_value = 0,
    },
    avionics = {
      target = "sim/operation/failures/rel_avionics",
      write_mode = "int",
      active_value = 6,
      inactive_value = 0,
    },
    electrical = {
      target = "sim/operation/failures/rel_elec",
      write_mode = "int",
      active_value = 6,
      inactive_value = 0,
    },
    airframe = {
      target = "sim/operation/failures/rel_structure",
      write_mode = "int",
      active_value = 6,
      inactive_value = 0,
    },
  }
}

local udp = nil

local function log(msg)
  print("[xplane-bridge] " .. tostring(msg))
end

local function parse_payload(text)
  if type(text) ~= "string" or text == "" then
    return nil
  end

  -- Fast path: parse the minimal JSON fields produced by the failure bot.
  local failure = text:match('"failure"%s*:%s*"([^"]+)"')
  local severity = tonumber(text:match('"severity"%s*:%s*([%-%%d%.]+)'))
  local event = text:match('"event"%s*:%s*"([^"]+)"')

  if not failure then
    return nil
  end

  return {
    failure = failure,
    severity = severity or 0,
    event = event or "unknown",
  }
end

local function write_target(mapping, severity)
  local is_active = tonumber(severity or 0) > 0
  local value = is_active and mapping.active_value or mapping.inactive_value

  if mapping.write_mode == "command_once" then
    if not is_active then
      return true
    end

    if type(command_once) == "function" then
      command_once(mapping.target)
      return true
    end

    return false, "command_once unavailable"
  end

  local ref = nil
  if type(find_dataref) == "function" then
    ref = find_dataref(mapping.target)
  end

  if not ref then
    return false, "dataref not found: " .. tostring(mapping.target)
  end

  if mapping.write_mode == "float" then
    ref = tonumber(value) or 0
  else
    ref = math.floor(tonumber(value) or 0)
  end

  return true
end

local function apply_payload(payload)
  local mapping = config.mappings[payload.failure]
  if not mapping then
    log("no mapping for failure: " .. tostring(payload.failure))
    return
  end

  local ok, err = write_target(mapping, payload.severity)
  if not ok then
    log("write failed: " .. tostring(err))
    return
  end

  log(string.format("applied event=%s failure=%s severity=%.2f", tostring(payload.event), tostring(payload.failure), tonumber(payload.severity) or 0))
end

local function poll_udp()
  if not udp then
    return
  end

  while true do
    local packet, err = udp:receive()
    if not packet then
      if err ~= "timeout" then
        log("udp receive error: " .. tostring(err))
      end
      break
    end

    local payload = parse_payload(packet)
    if payload then
      apply_payload(payload)
    else
      log("ignored payload (missing fields)")
    end
  end
end

local function init_udp()
  local sock, err = socket.udp()
  if not sock then
    log("udp init failed: " .. tostring(err))
    return false
  end

  local ok, bind_err = sock:setsockname("*", config.listen_port)
  if not ok then
    log("udp bind failed: " .. tostring(bind_err))
    return false
  end

  sock:settimeout(0)
  udp = sock
  log("listening on UDP port " .. tostring(config.listen_port))
  return true
end

local function main()
  if not init_udp() then
    return
  end

  if type(do_every_frame) == "function" then
    _G.xplane_bridge_generated_poll = poll_udp
    do_every_frame("xplane_bridge_generated_poll()")
    log("registered do_every_frame callback")
    return
  end

  if config.standalone_mode then
    while true do
      poll_udp()
      socket.sleep(0.02)
    end
  else
    log("do_every_frame unavailable; set standalone_mode=true for standalone mode")
  end
end

main()
